name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ secrets.SIGNING_STORE_JKS }}" > android-keys.txt
          base64 -d android-keys.txt > android-keys.jks

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
    
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build APK
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        with:
          arguments: assembleRelease

      - name: Build Bundle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        with:
          arguments: bundleRelease
      
      - uses: actions/upload-artifact@v3
        with:
          name: APK
          path: app/build/outputs/apk/release/*.apk

      - uses: actions/upload-artifact@v3
        with:
          name: Bundle
          path: app/build/outputs/bundle/release/*.aab

